name: Update cc posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-cc-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ayazhafiz.com/feed-rss2.xml"
          max_post_count: 3
          date_format: "mm/dd/yyyy"
          template: "$newline- [$title]($url) ($date)"
          commit_message: update cc
          committer_username: cc
          committer_email: cc@example.cc
